stages:
  - build
  - test
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build fe:
  image: node:16-alpine
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm build
    - npm run serve
