stages:
  - sync
  - build
  - test
  - deploy

sync:
  stage: sync
  script:
    - git remote add github https://github.com/elvizhuy/CGV-VueJs-Fe.git
    - git pull github master
    - git push origin master

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build fe:
  image: node:16-alpine
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm build
    - npm run serve
