const state = () => {
  return {
    DaysDate: [
      "Day",
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "11",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
      "18",
      "19",
      "20",
      "21",
      "22",
      "23",
      "24",
      "25",
      "26",
      "27",
      "28",
      "29",
      "30",
      "31",
    ],
    Months: [
      "Month",
      "January",
      "February",
      "March",
      "April",
      "May",
      "June",
      "July",
      "August",
      "September",
      "October",
      "November",
      "December",
    ],
    Years: [
      "Year",
      "2011",
      "2010",
      "2009",
      "2008",
      "2007",
      "2005",
      "2004",
      "2003",
      "2002",
      "2001",
      "2000",
      "1999",
      "1998",
      "1997",
      "1996",
      "1995",
      "1994",
      "1993",
      "1992",
      "1991",
      "1990",
      "1989",
      "1988",
      "1987",
      "1986",
      "1985",
    ],
    Regions: ["Region","Hà Nội","Hồ Chí Minh","Đà Nẵng","Hải Phòng","Thanh Hóa","Vĩnh Phúc","Cần Thơ","Đồng Nai","Quảng Ninh","Bà Rịa - Vũng Tàu","Bình Định","Bình Dương","Đắk Lắk","Trà Vinh","Yên Bái","Vĩnh Long","Kiên Giang","Hậu Giang","Kiên Giang","Hà Tĩnh","Phú Yên","Bình Phước","Cà Mau","Cao Bằng","Đắk Nông","Điện Biên","Đồng Tháp","Bắc Giang","Gia Lai","An Giang","Bạc Liêu","Hà Giang","Hà Nam","Bắc Cạn","Bắc Ninh","Bến Tre","Hà Tây","Hải Dương","Hòa Bình","Hưng Yên","Khánh Hòa","KonTum","Lai Châu","Lâm Đồng","Lạng Sơn","Lào Cai","Long An","Nam Định","Nghệ An","Ninh Bình","Ninh Thuận","Phú Thọ","Quảng Nam","Quảng Ngãi","Quảng Bình","Quảng Trị","Sóc Trăng","Sơn La","Tây Ninh","Thái Bình","Thái Nguyên","Thừa Thiên Huế","Tuyên Quang","Tiền Giang"],
    Sites: ["Prefer site","","","","","","","","","","","","","","","","","","","","","","","","","","","",],
  };
};

export default {
  namespaced: true,
  state,
};
